### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [thibaudcolas/dotfiles#3]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README.md`](https://github.com/thibaudcolas/dotfiles/blob/74d17dfc38fb4ba72c1a65c5ac7709ff1c448a54/README.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by thibaudcolas** [comment]
Thanks for the report! I’ve updated the link 🙂.
